max_epochs: null
max_steps: ${lr_scheduler.first_cycle_steps}
val_check_interval: 5000
check_val_every_n_epoch: null

accelerator: gpu
devices: ???
precision: bf16-mixed

gradient_clip_val: 1.0
accumulate_grad_batches: 16