# Data augmentation config file.
# This cfg leads to the instantiation of a MultisourceDataAugmentation object.
_target_: motif.data.data_aug.data_aug.MultisourceDataAugmentation
augmentation_functions:
  - _target_: motif.data.data_aug.era5_cropping.ERA5Cropping
    crop_frac_min: 0.3
    crop_frac_max: 1.0
    min_size: 21