# Data augmentation config file.
# This cfg leads to the instantiation of a MultisourceDataAugmentation object.
_target_: motif.data.data_aug.MultisourceDataAugmentation
augmentation_functions:
  # List of data augmentation classes
  - _target_: motif.data.data_aug.era5_recentering.ERA5GridRecentering