_target_: motif.lightning_module.deterministic.MultisourceDeterministicReconstructor
patch_size: 4
dim: ${model.dim}
coords_dim: ${model.coords_dim}
cond_dim: ${model.cond_dim}
n_sources_to_mask: 1
lr_scheduler_kwargs: ${lr_scheduler}
loss_max_distance_from_center: null
ignore_land_pixels_in_loss: false 
adamw_kwargs: ${optimizer}
coords_encoding_method: ${model.coords_encoding_method}
metrics: ${metrics}

backbone: ${model.backbone}