_target_: motif.lightning_module.flow_matching.MultisourceFlowMatchingReconstructor
patch_size: 4
dim: ${model.dim}
cond_dim: ${model.cond_dim}
n_sources_to_mask: 1
n_sampling_diffusion_steps: 25
n_realizations_per_sample: 10
lr_scheduler_kwargs: ${lr_scheduler}
loss_max_distance_from_center: null
adamw_kwargs: ${optimizer}
metrics: ${metrics}
use_det_model_from_run: null
cfg_scale: null
cfg_train_uncond_proba: 0.0
training_time_sampling: lognormal

backbone: ${model.backbone}
