# @package _global_
pred_name: fm

lightning_module:
  cfg_scale: null
  n_realizations_per_sample: 3

dataset:
  val:
    dt_max: 6
    min_ref_time_delta: 6
    groups_availability:
      pmw:
        sources: ['pmw']  # Includes all sources of type 'pmw'
        # Min, max number of sources from the group
        availability: [2, null]
    select_closest: true
  test:
    dt_max: ${dataset.val.dt_max}
    min_ref_time_delta: ${dataset.val.min_ref_time_delta}
    groups_availability: ${dataset.val.groups_availability}
    select_closest: ${dataset.val.select_closest}

