# @package _global_
pred_name: fm_cfg

lightning_module:
  cfg_scale: 1.0
  cfg_type: "chronological"
  n_realizations_per_sample: 3

dataset:
  val:
    dt_max: 6
    min_ref_time_delta: 6
    groups_availability:
      pmw:
        sources: ['pmw']  # Includes all sources of type 'pmw'
        # Min, max number of sources from the group
        availability: [2, null]
    select_most_recent: true
    forecasting_sources: null
    forecasting_lead_time: null
  test:
    dt_max: ${dataset.val.dt_max}
    min_ref_time_delta: ${dataset.val.min_ref_time_delta}
    groups_availability: ${dataset.val.groups_availability}
    select_most_recent: ${dataset.val.select_most_recent}
    forecasting_sources: ${dataset.val.forecasting_sources}
    forecasting_lead_time: ${dataset.val.forecasting_lead_time}

