# @package _global_
pred_name: gpm_dt1_multi

lightning_module:
  cfg_scale: null
  n_realizations_per_sample: 10
  mask_only_sources: ['tc_primed_pmw_GMI_GPM']

dataset:
  val:
    dt_min: -0.5
    dt_max: 0.5
    min_ref_time_delta: 1
    groups_availability:
      gpm:
        sources: ['tc_primed_pmw_GMI_GPM'] 
        availability: [1, 1]
      # At least 2 input pmw sources available.
      pmw:
        sources:
          - tc_primed_pmw_AMSR2_GCOMW1
          - tc_primed_pmw_TMI_TRMM
          - tc_primed_pmw_SSMI_F11
          - tc_primed_pmw_SSMI_F13
          - tc_primed_pmw_SSMI_F14
          - tc_primed_pmw_SSMI_F15
          - tc_primed_pmw_SSMIS_F16
          - tc_primed_pmw_SSMIS_F17
          - tc_primed_pmw_SSMIS_F18
          - tc_primed_pmw_SSMIS_F19
        # Min, max number of sources from the group
        availability: [2, 1000]  # Means no upper limit
    select_closest: false
  test:
    dt_max: ${dataset.val.dt_max}
    min_ref_time_delta: ${dataset.val.min_ref_time_delta}
    groups_availability: ${dataset.val.groups_availability}
    select_closest: ${dataset.val.select_closest}

