# @package _global_
pred_name: gpm_dt1

lightning_module:
  mask_only_sources:  # Only mask these sources when applying random source masking
    - tc_primed_pmw_GMI_GPM

dataset:
  val:
    dt_max: 1
    min_ref_time_delta: 1
    select_most_recent: true
    forecasting_sources: null
    forecasting_lead_time: null
    groups_availability:
      input:
        sources:
          - tc_primed_pmw_SSMI_F11
          - tc_primed_pmw_SSMI_F13
          - tc_primed_pmw_SSMI_F14
          - tc_primed_pmw_SSMI_F15
          - tc_primed_pmw_SSMIS_F16
          - tc_primed_pmw_SSMIS_F17
          - tc_primed_pmw_SSMIS_F18
          - tc_primed_pmw_SSMIS_F19
          - tc_primed_pmw_TMI_TRMM
          - tc_primed_pmw_AMSR2_GCOMW1
        # Min, max number of sources from the group
        availability: [1, null]
      target_gmi:
        sources: ['tc_primed_pmw_GMI_GPM']
        availability: [1, 1]
  test:
    dt_max: ${dataset.val.dt_max}
    min_ref_time_delta: ${dataset.val.min_ref_time_delta}
    select_most_recent: ${dataset.val.select_most_recent}
    forecasting_sources: ${dataset.val.forecasting_sources}
    forecasting_lead_time: ${dataset.val.forecasting_lead_time}
    groups_availability: ${dataset.val.groups_availability}

