# @package _global_
pred_name: pmw_ssl

dataset:
  val:
    dt_max: 6
    min_ref_time_delta: 6
    select_most_recent: true
    forecasting_sources: null
    forecasting_lead_time: null
  test:
    dt_max: ${dataset.val.dt_max}
    min_ref_time_delta: ${dataset.val.min_ref_time_delta}
    groups_availability: ${dataset.val.groups_availability}
    select_most_recent: ${dataset.val.select_most_recent}
    forecasting_sources: ${dataset.val.forecasting_sources}
    forecasting_lead_time: ${dataset.val.forecasting_lead_time}


lightning_module:
  forecasting_mode: false
  return_embeddings_in_predict: true
