dropout: 0.0
dim: 512
coords_dim: 256
cond_dim: 256
backbone:
  _target_: motif.models.motif.backbone.MultisourceGeneralBackbone
  n_blocks: 12
  dim: ${model.dim}
  att_inner_dim: ${model.dim}
  coords_dim: ${model.coords_dim}
  coords_inner_dim: ${model.coords_dim}
  cond_dim: ${model.cond_dim}
  num_heads: 16
  cross_att_window_size: 4
  iwsa_window_size: 8
  mlp_inner_ratio: 2.0
  dropout: ${model.dropout}
  downsample_input: false
