dropout: 0.0
values_dim: 256 # Will be doubled after each patch merging
coords_dim: 128
cond_dim: 128
backbone:
  _target_: motif.models.motif_double.unet_backbone.MultisourceGeneralBackboneUNet
  values_dim: ${lightning_module.values_dim}
  coords_dim: ${lightning_module.coords_dim}
  cond_dim: ${lightning_module.cond_dim}
  n_blocks_per_stage: [0, 12]
  dropout: ${model.dropout}
  att_inner_ratio: 1.0
  mlp_inner_ratio: 2.0
  num_heads: 8
  cross_att_window_size: 4
  iwsa_window_size: 8

output_resnet_blocks: null
output_resnet_channels: null