# Path to where the unpreprocessed datasets are stored
raw_datasets: "/home/cdauvill/scratch/data/motif/raw/"
# Path to where the preprocessed dataset will be saved
preprocessed_dataset: "/home/cdauvill/scratch/data/motif/preprocessed_pmw_concat/"
# Checkpoints directory
checkpoints: "/home/cdauvill/scratch/checkpoints/"
# Weights and Biases logs
wandb_logs: "/home/cdauvill/scratch/"
# Validation directory
validation: "/home/cdauvill/scratch/data/motif/validation"
# Predictions directory
predictions: "/home/cdauvill/scratch/data/motif/predictions"
# Results (including visualisation of predictions and targets)
results: "/home/cdauvill/scratch/data/motif/results"

gpm_tle_dir: "/home/cdauvill/scratch/data/motif/raw/gpm/tle"
gpm_granules_dir: "/home/cdauvill/scratch/data/motif/raw/gpm/granules/"
gpm_urls_dir: "/home/cdauvill/scratch/data/motif/raw/gpm/pmw_urls/"
gpm_cache_dir: "/home/cdauvill/scratch/data/motif/raw/gpm/cache/"
gpm_raw_coincidences_csv: "/home/cdauvill/scratch/data/motif/raw/gpm/raw_coincidences.csv"
gpm_coincidences_csv: "/home/cdauvill/scratch/data/motif/raw/gpm/coincidences.csv"
