# Path to where the unpreprocessed datasets are stored
raw_datasets: ${oc.env:WORK}/data/motif/raw/
# Path to where the preprocessed dataset will be saved
preprocessed_dataset: ${oc.env:SCRATCH}/data/motif/preprocessed_pmw_concat_regular/
# Checkpoints directory
checkpoints: ${oc.env:SCRATCH}/checkpoints/

wandb_logs: ${oc.env:SCRATCH}
validation: ${oc.env:SCRATCH}/data/motif/validation
predictions: ${oc.env:SCRATCH}/data/motif/predictions
results: ${oc.env:SCRATCH}/data/motif/results

