defaults:
  - _self_
  - paths: jz

# Whether to use a regular grid for PMW data
use_regular_grid_pmw: false
# Target resolution to which the PMW images will be regridded, in degrees.
# Give a list [longitude_res, latitude_res]
pmw_regridding_resolution: [0.15, 0.15]
# Target resolution for radar data, in km.
radar_regridding_resolution: 5.0
# Radar pre-selection: list of pairs (number of pixels, min rain rate) such
# that only radar images with at least that many pixels above that rain rate
# will be kept. Including multiple pairs will act as a logical OR.
radar_rain_rate_criteria: [[100, 10], [10, 100]]  # Values taken from Viltard et. al. 2024

# For ERA5 0.25Â° patches, size of the square patches in pixels
era5_patch_size: 201

# Fraction of the data to use when computing the normalization statistics
norm_constants_fraction: 1.0
# Minimum number of data points to use when computing the normalization statistics
norm_constants_min_samples: 100
# Maximum amount of memory per worker
max_mem_per_worker: "3.8GB"

# Split seasons for train, val, test sets. Indicate only the seasons that are
# included in the val and test sets; all other years will be used for training.
val_seasons: [2005, 2007, 2014, 2021, 2023]
test_seasons: [2006, 2008, 2015, 2022, 2024]
# Minimum time between two images from the same source over the same storm
# This is to avoid having very similar images in the dataset
min_time_between_same_source: 360  # in minutes