defaults:
  - paths: local
  - dataset: default
  - sources: pmw_37_89
  - data_augmentation: none
  - _self_


dataset:
  train:
    dt_max: 6
    num_workers: 0
  val:
    num_workers: 0
  
num_workers: 10

seed: 42
