# Keyword arguments of CosineAnnealingWarmupRestarts
interval: step  # Use training batches as the unit of the scheduler's step
warmup_steps: 1000
first_cycle_steps: 150000
check_val_every_n_epoch: null
cycle_mult: 1.0
max_lr: 3e-4
min_lr: 3e-6
gamma: 0.5
